### ISSUE TITLE
Follow sometimes does not click on the url

### ISSUE THREAD

**Issue by NouranMahmoud** [Adezandee/cucumber-mink#101]
I am facing a problem with my tests as (sometimes) the _follow does not redirect/click on the url_ .. and when I investigated this issue I found it related to phantomjs .. this is the error occurs to me 
`[DEBUG] Network - Resource request error: QNetworkReply::NetworkError(OperationCanceledError) ( "Operation canceled" ) URL: "http://localhost:8000/uae-en/categories/Clothing"` and this is the issues on phantomjs repo [issue1|https://github.com/ariya/phantomjs/issues/10389] and [issue2|https://github.com/ariya/phantomjs/issues/12750] and I couldn't find a solution ... anyway my question is .. do you in cucumber-mink community have any idea how can I fix this??

**Comment by NouranMahmoud** [comment]
I've used [selenium-standalone](https://github.com/vvo/selenium-standalone) with chrome driver and it worked fine.

**Comment by Adezandee** [comment]
Hi @NouranMahmoud, sorry never seen this issue before. Phantomjs isn't my default browser. I recommend using Chrome or Firefox with Selenium.
