### ISSUE TITLE
manyStep() returns `function accepts a callback and returns a promise`

### ISSUE THREAD

**Issue by pezholio** [Adezandee/cucumber-mink#105]
I'm using Cucumber Mink and I have some quite complex steps that I'd like factor out into a single step to make my scenarios a bit more legible, and I thought `Mink.manyStep` would fit the bill. However, I'm struggling to get this to work, as I get the error `function accepts a callback and returns a promise`. Here's what my step definition looks like:

```
Mink.When(/^I do my thing$/, function (callback) {
  Mink.manyStep([
    'I do thing 1',
    'I do thing 2',
    'I do thing 3',
    'I do thing 4'
  ], callback)
});
```

It's very possible I'm doing something wrong, would appreciate some guidance if I am! :) 

Thanks

**Comment by Adezandee** [comment]
Hi @pezholio, can you try something like that

```
Mink.When(/^I do my thing$/, function () {
  return Mink.manyStep([
    'I do thing 1',
    'I do thing 2',
    'I do thing 3',
    'I do thing 4'
  ])
});
```

**Comment by pezholio** [comment]
Perfect, that's got it. Thanks
