### ISSUE TITLE
sauce labs in travis

### ISSUE THREAD

**Issue by danielbush** [Adezandee/cucumber-mink#123]
Hi,
I'm trying to get cucumber-mink to run selenium tests against saucelabs from travis.  I have sauce connect (sc tool) on in travis.
I've tried every possible combination to try to get this to work.  I'm wondering if I'm configuring cucumber-mink and webdriverio correctly.  

Roughly what I'm trying is what I have below (based on `features/support/mink.js`):

```js
  { desiredCapabilities: 
      { browserName: 'internet explorer',
        platform: 'Windows 10',
        version: '11.103',
        'tunnel-identifier': '50.1',
        build: '50',
        name: 'integration',
      },
     host: username + ':' + accessKey + '@localhost',
     port: 4445,
     path: '/wd/hub',
 }
```

Am I configuring webdriver within cucumber-mink correctly?
Anybody else got this to work?

My run-script looks like this:

```
node_modules/.bin/cucumber-mink -- --require features/support --require features/step_definitions/
```

Sauce connect in travis says that selenium is listening on port 4445 within the travis console. 

I've successfully run karma using karma-sauce-launcher on saucelabs in travis.  The karma-sauce-launcher source code suggests it might be using a host ondemand.saucelabs.com on port 80.  It's using `wd`.  I've tried all of that as well.

I always get this (in travis):

```js
{ RuntimeError: Couldn't connect to selenium server
    at init() - anonymous function
  message: 'Couldn\'t connect to selenium server',
  type: 'RuntimeError',
  seleniumStack: 
   { status: -1,
     type: 'ECONNREFUSED',
     message: 'Couldn\'t connect to selenium server',
     orgStatusMessage: 'Couldn\'t connect to selenium server' } }
```

**Comment by Adezandee** [comment]
Hi @danielbush, can you try with this parameters :

``` js
const parameters = {
  driver: {
    desiredCapabilities: {
      browserName: 'internet explorer',
      platform: 'Windows 10',
      version: '11.103',
      'tunnel-identifier': '50.1',
      build: '50',
      name: 'integration',
    },
    /* host: ''  -- Default */,
    port: 4445,
    user: username,
    key: accessKey,
  },
};
```

**Comment by danielbush** [comment]
No.  Wasn't aware of `user` and `key` options.  But still not working.
I'll try to play with it some more.

**Comment by Adezandee** [comment]
@danielbush, or maybe since you're running the sauce tunnel on localhost, you don't even need user and key. Just the port `4445`

**Comment by danielbush** [comment]
Still can't get it to work.
I'm trying wd + mocha to change things up - but it's timing out.
Have a feeling I'm doing something stupid -__-
I guess we could close this.  If I get it working I'll come back and update it.
Thanks for helping.
