### ISSUE TITLE
How to access webdriver additional functions?

### ISSUE THREAD

**Issue by davidje** [Adezandee/cucumber-mink#166]
I have a step definition that clears all cookies and looks like this:
```
    this.Given(/^I am an anonymous user$/, function (callback) {
   //https://selenium.googlecode.com/git/docs/api/py/webdriver_remote/selenium.webdriver.remote.webdriver.html
   browser.manage().deleteAllCookies().then(callback);
   });
```

However, the way I am running the code (cucumber-mink -- -r mink.js etc), I am unable to get to 'browser' or 'browser.manage()'. 

If I try this.driver or this.driver.manage() -- no luck.

Also I have additional functionality that uses the Protractor driver (waitForAngular). Do I need to invoke cucumber-mink via cucumber-js to fix this problem? My other issue asks that thanks #163

**Comment by Adezandee** [comment]
Hello @davidje, if you're using protractor to run you suite, `global.browser` should be available in any files. You can check how I'm running during the Travis build or here https://github.com/Adezandee/cucumber-mink/blob/master/protractor.cucumber.js

**Comment by Adezandee** [comment]
If you're not using protractor driver, the webdriverio object is available on `MinkContext.driver.client`, see https://github.com/Adezandee/cucumber-mink/blob/master/src/drivers/webdriverio.js#L23
