### ISSUE TITLE
Ability to check cookies

### ISSUE THREAD

**Issue by danielanteloagra** [Adezandee/cucumber-mink#215]
Step definitions allowing to check if a cookie exists would be great.

Worth considering, thanks,

**Comment by Adezandee** [comment]
@danielanteloagra could be handy 👍

**Comment by nishsinghal** [comment]
@Adezandee Seems like cookies can be checked using webdriver: http://webdriver.io/api/cookie/getCookie.html#
Would be awesome if there were built in definitions for these, I can make a PR if you like
