### ISSUE TITLE
handling redirects

### ISSUE THREAD

**Issue by benoitpointet** [Adezandee/cucumber-mink#232]
It seems that cucumber-mink does not by defaut handle redirects transparently (at least with phantomjs).

I could come over some the redirect issues i encountered by adding a "I wait 1 seconds" step.

Why isn't handling redirects? feature or bug?

**Comment by Adezandee** [comment]
If you are triggering redirect with javascript, there is no way cucumberjs can detect those. There is simply no interaction between backend javascript (cucumber) and frontend javascript (phantomjs).
Selenium isn't capable of propagating such event to backend js. So, I would say feature.
