### ISSUE TITLE
Failing assertions hang

### ISSUE THREAD

**Issue by lsjroberts** [Adezandee/cucumber-mink#24]
The `assertFn(...)` calls appear to hang whenever an assertion fails. It doesn't output the step name, just remains stuck after the previous successful step.

I am using version `1.0.1`.

For example with `I should see "foo"` I added a `console.log` before and after the call to `assertFn(html, expectedText)` in [assert-dom.js](https://github.com/Adezandee/cucumber-mink/blob/master/lib/step_definitions/ext/assert-dom.js#L19). The second log is never reached when the html doesn't include `foo`, but is when the html does include `foo`.

I tested a `try...catch` block around it and the `AssertionError` is thrown correctly, so it does appear the issue is not with chai as far as I can tell.

**Comment by lsjroberts** [comment]
I've been running it through `grunt-cucumber`, doing this causes it to hang.

Testing it with `cucumber-js` directly actually just causes it to end the process at the failing test (still without outputting it to the terminal).

**Comment by lsjroberts** [comment]
Essentially it looks like the `AssertionError` thrown by chai isn't caught correctly in cucumber-mink.

I wrote a quick example to test it outside of cucumber-mink which confirmed it isn't a problem with chai or cucumber:

```
  Scenario: This is a failing scenario
    When I go to the homepage
    Then I should be on "/login"
    And failing example
    And I should see "this text doesn't exist"
```

```js
var chai = require('chai');

module.exports = function () {
  this.Then(/^failing example$/, function (callback) {
    try {
      chai.assert.include('foo', 'bar');
    } catch (e) {
      callback(e.toString());
    }
  });
}
```

Not sure where to take it from here, sorry!

**Comment by Adezandee** [comment]
Hi @lsjroberts,
Thanks again for your feedback, i'll look into it quickly :)

**Comment by Adezandee** [comment]
@lsjroberts i made some changes in #25, can you test it with your custom runner ?

**Comment by lsjroberts** [comment]
@Adezandee Sure will do, I'll give a run when I'm back in the office tomorrow

**Comment by lsjroberts** [comment]
@Adezandee Yep, that works correctly thanks very much :)

**Comment by Adezandee** [comment]
@lsjroberts Great, gonna merge it and release a fix aka. v1.0.2.
I released a new documentation page also, http://cucumber-mink.js.org/steps/
don't hesitate if you have any feedback about it, missing step etc. Thanks !
