### ISSUE TITLE
manySteps not behaving as scenario

### ISSUE THREAD

**Issue by benoitpointet** [Adezandee/cucumber-mink#240]
I have the following 'login' scenario

```
  Scenario: Login as Caroline
    Given I browse "http://example.lo/"
    When I am on "/signout/" #signs out and redirects to signin screen
    And I press "a.btn-signin"
    And I fill in "input#email" with "caroline@example.com"
    And I press "input#submit-login"
    Then I should see "Caroline"
```

It works well as such.

I make a single step out of it:

```
Mink.defineStep(/^I login as "([^"]*)"$/, function(email, callback){
  Mink.manyStep([
    'I am on "/signout/"',
    'I press "a.btn-signin"',
    'I fill in "input#email" with "' + email + '"',
    'I press "input#submit-login"',
  ]);
  callback();
});
```

and adapt the scenario:

```
  Scenario: Login as Caroline
    Given I browse "http://example.lo/"
    When I login as "caroline@example.com"
    Then I should see "Caroline"
```

The scenario fails.

I went so far as to see that the "fill in" step does not perform in the manyStep version, no clue why.

Any hints?

**Comment by Adezandee** [comment]
Hi @benoitpointet,
yeah, rewrite your step like this:
``` js
Mink.defineStep(/^I login as "([^"]*)"$/, function(email, callback){
  Mink.manyStep([
    'I am on "/signout/"',
    'I press "a.btn-signin"',
    'I fill in "input#email" with "' + email + '"',
    'I press "input#submit-login"',
  ], callback);
});
```

**Comment by benoitpointet** [comment]
Thx. Solved the case.

If I use your proposal, then an error occurs saying "Function requires a callback and returns a Promise".

I ended up removing the callback completely. Works for me.

Question: are any callbacks passed by default or is the callback construction only for specific callbacks that cucumber-mink users would implement?

**Comment by Adezandee** [comment]
cucumber support either a function with a callback or returning a Promise.
The way it detects between those two should be checked inside the cucumberjs repository
