### ISSUE TITLE
Should be on is not working with parameters

### ISSUE THREAD

**Issue by cajoy** [Adezandee/cucumber-mink#257]
For example I have following urls in menu:

/info/?page=terms

So I click on a link and I would like to verify that I am landed where expected

Then I should be on "/info/?page=terms" - doesn't work
while
Then I should be on "/info/" - works fine

What is kind of unexpected.

**Comment by Adezandee** [comment]
Yeah, that's because I use nodejs `url` package to parse the raw url requested to the selenium server.
You could however implement your own check step which retrieve the same raw url.

**Comment by cajoy** [comment]
Thanks @Adezandee  I will create new step..
