### ISSUE TITLE
How can I clear cookie, session after each "feature"?

### ISSUE THREAD

**Issue by cajoy** [Adezandee/cucumber-mink#258]
For example I have 5 feature files 

One of them Sign in user

I want to have clear session for each feature file. How can achieve it using framework?

**Comment by Adezandee** [comment]
You can use the underlying `webdriverIO` API to do that. It's available through `Mink.driver`.
See the API http://webdriver.io/api.html

**Comment by cajoy** [comment]
Unfortunately I can't make it work

```
module.exports = function () {
    Mink.init(this, parameters);

    Mink.cucumber.BeforeFeature(function (test) {
      // console.dir('1', Mink.driver.browser, true)
      // console.dir('2', Mink.driver.deleteCookie(), true)
      // console.dir('3', Mink.browser.deleteCookie(), true)
      // console.dir('4', Mink.driver.browser.deleteCookie(), true)
    })
};
```

It is always undefined. How can I get browser instance???
