### ISSUE TITLE
Enhanced support for AngularJS

### ISSUE THREAD

**Issue by mattbullock** [Adezandee/cucumber-mink#26]
Cucumber steps are prone to failing inconsistently while waiting for Angular's digest loop to complete, depending on the duration of the loop, and perhaps other factors. The Cucumber-Mink steps are awesome and I'd like to use them in my Angular project.

Do you plan to add support for Angular-based projects?

Or, how can we use Mink with another library, like Protractor, which works more nicely with Angular? Both libraries wrap the webdriver-io instance. It would be great if we could use Mink's steps with Protractor's wrapped webdriver, so that we get Mink's well-considered steps on top of an Angular-friendly driver.

**Comment by matmar10** [comment]
:+1: would love to see AngularJS support. We tried to use mink in the project I'm working on now but also ran into this issue.

**Comment by Adezandee** [comment]
Well it would certainly be awesome to support Angular based projects, i'll take a look and try testing the Angular Todo app. I don't know either if hooking Protractor can be easily done though.
I'm open for any kind of insight / PR on this topic.
(Well, if supporting Protractor needs a full driver api rewrite, maybe we'll need to fire up a new repository for that)

**Comment by Adezandee** [comment]
@mattbullock @matmar10 

I extracted the magic method of protractor for angular app with selenium browser and implemented a fairly simple cucumber hook:

```javascript
// features/support/angular.js
var Mink = require('cucumber-mink');

module.exports = function() {
  this.registerHandler('AfterStep', function(event, callback) {
    var waitForAngular = function(rootSelector, callback) {
      var el = document.querySelector(rootSelector);
      try {
        if (!window.angular) {
          throw new Error('angular could not be found on the window');
        }
        if (angular.getTestability) {
          angular.getTestability(el).whenStable(callback);
        } else {
          if (!angular.element(el).injector()) {
            throw new Error('root element (' + rootSelector + ') has no injector.' +
              ' this may mean it is not inside ng-app.');
          }
          angular.element(el).injector().get('$browser').
            notifyWhenNoOutstandingRequests(callback);
        }
      } catch (err) {
        callback(err.message);
      }
    };
    Mink.driver.client.executeAsync(waitForAngular, '#todoapp').then(function(ret) {
      console.log(ret);
      callback();
    });
  });
};
```

I tested with an app making async request with $http, and it works pretty well. Could you guys try this snippet on your apps and let me know if it works. Thanks

**Comment by matmar10** [comment]
This is awesome, @Adezandee but I'm having trouble getting mink to open the initial page. 

No matter what I put for `Given I browse "http://localhost:9000"`only `data:,` is ever opened in Chrome.

- Using local Chrome
- Starting webdriver with `webdriver-manager start`
- Running with `./node_modules/cucumber/bin/cucumber.js --require features/support/local-chrome.js`

Support file has:
```
var mink = require('cucumber-mink');
var parameters = {
  driver: {
    desiredCapabilities: {
      browserName: 'chrome'
    }
  }
};

module.exports = function () {
  mink.init(this, parameters);
};
```
Any ideas? I'm having trouble getting started but looking forward to testing out the angularjs support branch.

package.json
---
* "cucumber": "^0.6.0"
* "cucumber-mink": "git+https://github.com/Adezandee/cucumber-mink.git#feature/angularjs-support",

**Comment by Adezandee** [comment]
Hi @matmar10,
I know this issue is quite old but I've just added a new driver interface that allows to use `cucumber-mink` with protractor (through `protractor-cucumber-framework` package). See https://github.com/Adezandee/cucumber-mink/releases/tag/v1.3.0
It's still quite experimental, I'll use it right away on a big angular project though.

**Comment by matmar10** [comment]
@Adezandee very cool - sing cucumber on a new project so will have a go with it

**Comment by Adezandee** [comment]
Migration to puppeteer should now ensure full angular compatibility, provided that you configure the driver "wait" hooks on relevent angular events.
