### ISSUE TITLE
Separate step definitions from webdriver management

### ISSUE THREAD

**Issue by mattbullock** [Adezandee/cucumber-mink#27]
It would be great to use Mink's step definitions without the library creating and managing the webdriver-io instance.

Any plans to make the managed webdriver instance configurable? I'd love to pull just the steps into my project and manage the driver instance separately, but I see they are tightly coupled.

**Comment by Adezandee** [comment]
Hi @mattbullock,
Well it could be easily configurable with few changes but you'll have to provide a Driver object with all methods declared in https://github.com/Adezandee/cucumber-mink/tree/master/lib/driver/methods
Indeed its tightly coupled, still i created my own set of Driver "API", so you can hook in pretty nicely with another Driver object
Is this what you meant ?

**Comment by Adezandee** [comment]
As of now, my own Driver object instantiate a WebDriverIO client, that i use internally by calling "this.client".
