### ISSUE TITLE
Driver baseUrl param not being used from support/mink.js

### ISSUE THREAD

**Issue by jrschumacher** [Adezandee/cucumber-mink#319]
Doing exactly what is done in #22 using v1.6.0 of cucumber mink results in the base url not being set.

This is the directory tree

```
features
  |-- support
      |-- mink.js
```

Command: `cucumber-mink`

---

If I run `BASE_URL=http://google.com cucumber-mink` it works.

**Comment by Adezandee** [comment]
Should work as intended... dunno ?
