### ISSUE TITLE
Support for cucumber 3.0.0

### ISSUE THREAD

**Issue by benoitpointet** [Adezandee/cucumber-mink#322]
Cucumber-mink does not work with cucumber 3.0.0, due to some breaking changes on the cucumber-js side: https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md

**Comment by fgiroud** [comment]
+1 for this

**Comment by Adezandee** [comment]
Thanks for the report, I'll work on this

**Comment by Adezandee** [comment]
@benoitpointet @fgiroud 
done https://github.com/Adezandee/cucumber-mink/releases/tag/v1.7.0

**Comment by fgiroud** [comment]
Thanks a lot! that was fast
