### ISSUE TITLE
How to run cucumber-mink in remote machine using Selenium-grid's hub and node mode

### ISSUE THREAD

**Issue by AniteSridhar** [Adezandee/cucumber-mink#33]
I have started hub using following command:
"java -jar C:\Selenium\selenium-server-standalone-2.43.1.jar -role hub"
and node
"java -jar C:\Selenium\selenium-server-standalone-2.43.1.jar -role webdriver -hub http://localhost:4444/grid/register -port 8910 -browser browserName="chrome",version=ANY,platform=WINDOWS,maxInstances=5 -Dwebdriver.chrome.driver=C:\Selenium\chromedriver_win32\chromedriver.exe phantomjs --webdriver=8080 --webdriver-selenium-grid-hub=http://127.0.0.1:4444"
but when I am executing chrome browser is not opening instead headless execution using Phantomjs is happening.. Please advice me how to proceed..

**Comment by Adezandee** [comment]
Hi @AniteSridhar,
If your using the CLI, try : `cucumber-mink --browser chrome --port 4444`
Otherwise, if your using cucumber CLI with support file, take a look at https://github.com/Adezandee/cucumber-mink/blob/master/examples%2Flocal-chrome.js
