### ISSUE TITLE
Hangs on start, phantomjs running

### ISSUE THREAD

**Issue by chadfurman** [Adezandee/cucumber-mink#36]
$ phantomjs --version
1.9.8
$ node --version
v4.2.1
$ cucumber-mink 
Cucumber-mink v1.0.2. Launching phantomjs on port 8910...

and then it just sits there?

**Comment by Adezandee** [comment]
Hi @chadfurman sorry the wording is misleading, it should be `connecting` instead of launching. You have to launch phantomjs in another terminal with `$ phantomjs -w`.

**Comment by chadfurman** [comment]
phantomjs was running.  For some reason, restarting fixed.  It just worked this morning.
