### ISSUE TITLE
Phantomjs 2.1 cannot connect to selenium server?

### ISSUE THREAD

**Issue by chadfurman** [Adezandee/cucumber-mink#45]
Just installed the latest phantomjs 2.1 and cucumber-mink cannot connect to it?

**Comment by chadfurman** [comment]
this isn't the case on 1.0.2 but it is on 1.1.0

**Comment by Adezandee** [comment]
hi @chadfurman,
I changed the default browser settings, I've ran the e2e tests with phantomjs 2.1 with this command:
`cucumber-mink --browser phantomjs --port 8910 -- test/`
I experienced too many issues with phantomjs, I'm mainly using Firefox now. It's easy done with [webdriver-manager](https://github.com/pose/webdriver-manager).

``` bash
$ npm i -g webdriver-manager
$ webdriver-manager update --standalone
$ webdriver-manager start
```
