### ISSUE TITLE
Configuration options lost

### ISSUE THREAD

**Issue by rande** [Adezandee/cucumber-mink#72]
Hello,

While trying to use browserstack as a selenium remote server:

```js
// features/support/mink.js

var Mink = require('cucumber-mink');

// BrowserStack
var parameters = {
    driver: {
        desiredCapabilities: {
            'browserstack.local': true,
            'browserstack.debug': true,
            browser:              'Safari',
            browser_version:      '8.0',
            os:                   'OS X',
            os_version:           'Yosemite',
            resolution:           '1280x1024',
            build:                'Test'
        },
        host:                'hub.browserstack.com',
        port:                80,
        user:                'XXXXXXXXXX',
        key:                 'XXXXXXXXXXXXXXXXXXXX',
        logLevel:            'verbose'
    }
};

console.log("mink.js init script");

module.exports = function () {
    Mink.init(this, parameters);
};
```

with a single feature: 

```specs
Feature: Post page

  Background:
    Given I browse "https://thomas.rabaix.net/"

  Scenario: Go on post 1
    Given I am on homepage
    And I follow "Resume"
    Then I should be on "/resume/fr"
```

The command is started with: ``node_modules/.bin/cucumber-mink -- -r features/support/mink.js``

I get 

```
RuntimeError: Couldn't connect to selenium server
    at init([object Object]) - anonymous function
```

I dig into the code and I found out that the ``registerHook`` method (https://github.com/Adezandee/cucumber-mink/blob/master/src/mink.js#L167) is reseting the ``unit`` monad from webdriverio. So we are loosing the original values.

If I output some the hostname value, I get 
```
WebdriverIO Monad hub.browserstack.com  // original configuration value
WebdriverIO Monad 127.0.0.1                       // reset from the hook ...
WebdriverIO Monad 127.0.0.1
WebdriverIO Monad 127.0.0.1
``` 

Something is wrong on my side ?

**Comment by pebie** [comment]
:+1:

**Comment by Adezandee** [comment]
@rande @pebie, working on it thx for feedback 👍

**Comment by Adezandee** [comment]
@rande, can you test it with:
`$ node_modules/.bin/cucumber-mink --inject false -- -r features/support/mink.js`

**Comment by rande** [comment]
@Adezandee same issue.

**Comment by rande** [comment]
@Adezandee do you manage to reproduce the issue ?

**Comment by Adezandee** [comment]
I pushed 2 fixes following some investigation on your issue, I'm able to get WebdriverIO to connect to browserstack now yes

**Comment by pebie** [comment]
@Adezandee I ran into a new issue with --inject flag.

I'm able to get WebdriverIO connect to browserstack but I have this issue 

Error: A session id is required for this command but wasn't found in the response payload

**Comment by Adezandee** [comment]
@rande, could you please run mink with `DEBUG` and show me the output if you experience any other issues ?
`$ DEBUG=mink:* cucumber-mink --inject false`

**Comment by Adezandee** [comment]
@pebie, yeah I'm seeing that too. I'll dig into WebdriverIO / BrowserStack interaction

**Comment by pebie** [comment]
@Adezandee 

After running : 

`DEBUG=mink:* ./node_modules/.bin/cucumber-mink --inject false -- -r ./e2e/support/index.js ./e2e/features`

I get : 

`mink:cli [ 'node', 'cucumber-js', '-r', './e2e/support/index.js', './e2e/features' ]`

**Comment by pebie** [comment]
Your catch statement 

[https://github.com/Adezandee/cucumber-mink/blob/master/src/mink.js#L172](https://github.com/Adezandee/cucumber-mink/blob/master/src/mink.js#L172)

````javascript
registerHooks(cucumber, driver) {
    cucumber.registerHandler('BeforeFeatures', (event, done) =>
      driver.init()
        .then(() => (
          driver.setViewportSize(driver.parameters.viewportSize)
        ))
        .then(() => done())
        .catch(function(error){
            console.log(error);
            done();
        });
    );
````

By changing the catch statement I saw that the issue was due to browserstack tunnel connection. So I try to connect it and now it's work ;)

**Comment by Adezandee** [comment]
@pebie great 👍  
I'll clean this up now, thanks

**Comment by pebie** [comment]
@Adezandee thx :+1: 

It's work fine 

Cheers

**Comment by rande** [comment]
@Adezandee I am back again, sorry I was off for a few day.

The issue is still present with your 1.2.2 release. I have the same behavior. Please note, I have reinstall all packages from a clean state (``rm -rf node_modules``).

**Comment by rande** [comment]
For information; @pebie is using BrowserStackLocal to test internal websites so the default values are working (127.0.0.1:4444). However if we set hub.browserstack.com in the configuration to test public websites then we hit the issue : 

```
WebdriverIO Monad hub.browserstack.com
WebdriverIO Monad 127.0.0.1
WebdriverIO Monad 127.0.0.1
WebdriverIO Monad 127.0.0.1
WebdriverIO Monad 127.0.0.1
{ [Error: Couldn't connect to selenium server]
  message: 'Couldn\'t connect to selenium server',
  type: 'RuntimeError',
  seleniumStack:
   { status: -1,
     type: 'ECONNREFUSED',
     message: 'Couldn\'t connect to selenium server',
     orgStatusMessage: 'Couldn\'t connect to selenium server' } }
```

**Comment by pebie** [comment]
@rande 

I think it's just a matter port that is used by selenium in local mode.

By default it's 4444. In your local driver configuration try to change it.

FYI it's work for me even without browserstack.

**Comment by rande** [comment]
@pebie my use case is simple, I want to use selenium server provided by browser stack to test a public site. This use case does not work.

**Comment by Adezandee** [comment]
@rande, maybe you're initializing Mink twice, try running it with `DEBUG` flags to se if `mink init` message appears two times.
IE: `DEBUG=* node_modules/.bin/cucumber-mink -- -r features/support/mink.js`

**Comment by rande** [comment]
@Adezandee I create a small project with the failing test: https://github.com/rande/browserstack-kitchensink

**Comment by Adezandee** [comment]
@rande, works here. Juste a little change since you're not using `local` browserstack, you have to set
```
───────────────
modified: features/support/mink.js
───────────────
@ mink.js:7 @ var Mink = require('cucumber-mink');
var parameters = {
    driver: {
        desiredCapabilities: {
            'browserstack.local': true,
            'browserstack.local': false,
            'browserstack.debug': true,
            browser:              'Safari',
            browser_version:      '8.0',
```

**Comment by rande** [comment]
@Adezandee cannot manage to make it work with your settings. However, as @pebie pointed out, with ``--inject false`` it works.

**Comment by Adezandee** [comment]
@rande, see https://github.com/rande/browserstack-kitchensink/pull/1

**Comment by rande** [comment]
Ok, here my finding:

* using ``node_modules/.bin/cucumber-mink -- -r features/support/mink.js`` then ``browserstack.local`` are not used and tests are failling unless ``--inject false`` is provided. 
* using ``cucumber-js`` directly make tests working with no configuration option.

My conclusion is that ``browserstack.local`` is not required, and the ``cucumber-mink`` documentation should clearly state the 2 options to start the command. Currently, this is no clear at all. As @Adezandee states in rande/browserstack-kitchensink#1, the documentation should only refer to ``cucumber-js`` as it works out of the box.
