### ISSUE TITLE
callback function not called in manyStep()

### ISSUE THREAD

**Issue by chombium** [Adezandee/cucumber-mink#97]
Hi,

I want to hide the technical steps (clicks, input fields values insertion...) from the business features (like, I can login, I can search for, etc). 
To do a small tests I wrote a small test which opens https://twitter.com clicks the log in button and then on the new page inserts the values for the username and password fields.
Actually I wanted to test if when I use manyStep definition I could hide the printout of the username and password values when cucumber runs the scenarios

Therefore I tried using the manyStep step definition as follows:
My step definition looks as follows:

`
var Mink = require('cucumber-mink');

function manyStepTest(callback) {
    Mink.manyStep([
                   'I click on "button.submit"',
                   'I fill in "input[name=\'session[username_or_email]\']" with "Teeest"',
                   'I fill in "input[name=\'session[password]\']" with "Teeest"',
                 ], callback);
    callback(); // hack because that the callback is not used in Mink.manyStep()
}

module.exports = function() {
  this.Given(/^I do many steps$/, manyStepTest);
};
`

and my feature looks like this:
`
Feature: I can login on twitter

  Background:
    Given I browse "https://twitter.com/"

  Scenario: Twitter login
    When I am on the homepage
    Given I do many steps
    Then I should see "twitter"
`

When I ran the  feature without the last "callback();" in the function manyStepTest from the step definition I got a timeout error:
`
Feature: I can login on twitter

  Scenario: Twitter login
    Given I browse "https://twitter.com/"
    When I am on the homepage
    Given I do many steps
    Then I should see "twitter"

Failures:

1) Scenario: Twitter login - features/home.feature:6
   Step: Given I do many steps - features/home.feature:8
   Step Definition: features/step_definitions/login.js:49
   Message:
     function timed out after 5000 milliseconds

1 scenario (1 failed)
4 steps (1 failed, 1 skipped, 2 passed)
0m08.543s
`

With the callback function added, the feature passes without problems:
`
Feature: I can login on twitter

  Scenario: Twitter login
    Given I browse "https://twitter.com/"
    When I am on the homepage
    Given I do many steps
    Then I should see "twitter"

1 scenario (1 passed)
4 steps (4 passed)
0m01.203s
`

The Cucumber Mink version which I use is: cucumber-mink@1.2.2

I've checked the source code and I found the manyStep definition in dist/mink.js and src/mink.js but the callback is missing and the function signature is:
function manyStep(lines).

Am I missing something in my manyStep definition? Is a call of the callback function missing in the implementation of the manyStep function or it I must call the callback manually like I did in my step definition?

Best Regards,
Jovan

**Comment by Adezandee** [comment]
Hi @chombium,
Thanks for your feedback, indeed the callback parameter is not handled due to recent changes.
In the meantime you can use:
```js
Mink.manyStep([
  'I click on "button.submit"',
  'I fill in "input[name=\'session[username_or_email]\']" with "Teeest"',
  'I fill in "input[name=\'session[password]\']" with "Teeest"',
]).asCallback(callback);
```

**Comment by Adezandee** [comment]
You may also directly return the promise since cucumber runner will handle it directly

**Comment by chombium** [comment]
Hi @Adezandee,
thanks for the fast reply and the suggested solutions.
Can you please tell me if you have planed any changes of the manyStep function regarding the callback, so that I know if I need to refactor my step definitions in future

BR,
Jovan
